"""create fa_cases table

Revision ID: 084d0727ee15
Revises: 
Create Date: 2026-08-10 14:35:49.090533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084d0727ee15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fa_cases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('fail_type', sa.String(length=100), nullable=False),
    sa.Column('fail_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fa_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fa_cases_case_id'), ['case_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fa_cases_fail_type'), ['fail_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fa_cases_product'), ['product'], unique=False)
        batch_op.create_index(batch_op.f('ix_fa_cases_project'), ['project'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fa_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fa_cases_project'))
        batch_op.drop_index(batch_op.f('ix_fa_cases_product'))
        batch_op.drop_index(batch_op.f('ix_fa_cases_fail_type'))
        batch_op.drop_index(batch_op.f('ix_fa_cases_case_id'))

    op.drop_table('fa_cases')
    # ### end Alembic commands ###
